### ISSUE TITLE
create account failed

### ISSUE THREAD

**Issue by 2490037594** [playerone-id/EosCommander#22]
When I create account with Default wallet, but if failed at "signAndPackTransaction----- mNodeosApi.getRequiredKeys".   onError: {"code":401,"message":"UnAuthorized","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[]}}. Thanks!

**Comment by 2490037594** [comment]
available_keys:[EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV]
transaction:
{
  "context_free_data": [],
  "signatures": [],
  "actions": [
    {
      "account": {
        "mValue": 6138663577826886000
      },
      "authorization": [
        {
          "actor": {
            "mValue": 6138663577826886000
          },
          "permission": {
            "mValue": 3617214756542218000
          }
        }
      ],
      "data": "0000000000ea3055e0689bf0b573de6b0100000001000316e7a7c3912d794532132f5fee7a551fe4bdad8212c527a3b818ea827c318fa60100000001000000010003e55bc18da808c6d02f30fbe68b4c4eccf2ded6b33a67299b1e22118f3fb9dd8a01000000",
      "name": {
        "mValue": -7297973096368161000
      }
    },
    {
      "account": {
        "mValue": 6138663577826886000
      },
      "authorization": [
        {
          "actor": {
            "mValue": 6138663577826886000
          },
          "permission": {
            "mValue": 3617214756542218000
          }
        }
      ],
      "data": "0000000000ea3055e0689bf0b573de6b01000000000000000453595300000000",
      "name": {
        "mValue": 4520896354024685600
      }
    },
    {
      "account": {
        "mValue": 6138663577826886000
      },
      "authorization": [
        {
          "actor": {
            "mValue": 6138663577826886000
          },
          "permission": {
            "mValue": 3617214756542218000
          }
        }
      ],
      "data": "0000000000ea3055e0689bf0b573de6b010000000000000004535953000000000100000000000000045359530000000000",
      "name": {
        "mValue": 5378043540636893000
      }
    }
  ],
  "context_free_actions": [],
  "transaction_extensions": [],
  "delay_sec": 0,
  "expiration": "2018-08-19T02:53:57",
  "max_cpu_usage_ms": 0,
  "max_net_usage_words": 0,
  "ref_block_num": 10421907,
  "ref_block_prefix": 72067987
}

**Comment by 2490037594** [comment]
Setting------ Set Connection, Connected,  Core asset symbol, I choose "SYS";   Set skipping signatures, I check it .

**Comment by swapnibble** [comment]
Uncheck the option "Set skipping signatures".
