### ISSUE TITLE
signature action

### ISSUE THREAD

**Issue by TBoyLi** [playerone-id/EosCommander#25]
Where is the signing action in the source code？I just saw this。
![image](https://user-images.githubusercontent.com/14815341/54325802-ff7fe800-463e-11e9-8661-a46f299d488b.png)

**Comment by swapnibble** [comment]
scroll more lines down. ;)

see https://github.com/playerone-id/EosCommander/blob/6010082845cf96040c4d41bd101da9cdb7448feb/app/src/main/java/io/plactal/eoscommander/data/EoscDataManager.java#L214
